title: Hakan Dagli # your name (or website title) here
logo: "/images/IMG_9346.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I’m passionate about using data and AI to tackle real-world business challenges and exploring how these technologies are shaping our future. Currently, I’m learning about Sparse Convolutional Neural Networks for object detection, understanding the boundaries of what machine learning can achieve. 
  <br><br>
  May 2026 - B.S. in Data Science; Business Analytics (Minor), William & Mary
  <br><br>
  <a href="https://www.linkedin.com/in/hakan-dagli9/">View My LinkedIn Profile</a>
  <a href="https://github.com/hakandagli09">View My GitHub Profile</a>

  
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
